// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/Bloomberg.tsx": () => import("../components/mockups/dashboard/Bloomberg.tsx"),
  "./components/mockups/dashboard/DarkPro.tsx": () => import("../components/mockups/dashboard/DarkPro.tsx"),
  "./components/mockups/dashboard/Institutional.tsx": () => import("../components/mockups/dashboard/Institutional.tsx")
};
